-- MySQL Script generated by MySQL Workbench
-- jeu 17 aoû 2017 16:19:47 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema messages
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema messages
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `messages` DEFAULT CHARACTER SET utf8 ;
USE `messages` ;

-- -----------------------------------------------------
-- Table `messages`.`envoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages`.`envoi` (
  `id` INT NOT NULL,
  `message à envoyer` VARCHAR(255) NOT NULL,
  `pseudo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messages`.`reception`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages`.`reception` (
  `id` INT NOT NULL,
  `pseudo` VARCHAR(255) NOT NULL,
  `envoi_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reception_envoi_idx` (`envoi_id` ASC),
  CONSTRAINT `fk_reception_envoi`
    FOREIGN KEY (`envoi_id`)
    REFERENCES `messages`.`envoi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
